### ISSUE TITLE
老哥，你的雪碧图过期了……

### ISSUE THREAD

**Issue by ZhaZhengRefn** [lenvonsam/vuejs-emoji#2]
辛苦了 ，但是文档有错误而且雪碧图过期了。

`[class*="sprite-"]{width:25px;height:25px;background:url("https://dn-mhke0kuv.qbox.me/040f035c9371f257fa35.png");background-repeat:no-repeat;`

https://dn-mhke0kuv.qbox.me/040f035c9371f257fa35.png

**Comment by lenvonsam** [comment]
Please npm install last version of vuejs-emoji
